### ISSUE TITLE
n00b coding part III

### ISSUE THREAD

**Issue by ryancor** [dv1pr/python-drinking-game#3]
https://github.com/dv1pr/python-drinking-game/blob/3b203c67c225acab50c9e385a20c28d4870211cb/drinking_game.py#L84

you dont need an elif, once you make the conditional that the number will be greater, all else will be lower... " elif guess < secret_num " can just turn into " else "

**Comment by the-dvlpr** [comment]
I was purposely avoiding the case of if the guess was == but I caught that earlier. Thanks for pointing that out my man!
